### ISSUE TITLE
Fragment masking over React Client & Server Components

### ISSUE THREAD

**Issue by hrougier** [0no-co/gql.tada#223]
### Describe the bug

Using the following stack:
- next 14.2.1
- @apollo/experimental-nextjs-app-support 0.10.0

With fragment masking over react client & server components:

`page.tsx` (Server Component)
```tsx
import { graphql } from "gql.tada";
import { apollo } from "@/graphql/server";
import Character, { CharacterFragment } from "./Character";

const query = graphql(
  `
    query Character {
      character(id: "1") {
        ...Character
      }
    }
  `,
  [CharacterFragment],
);

export default function Character() {
  const client = apollo();
  const {
    data: { character },
  } = await client.query({ query });

  return <Character character={character} />;
}
```

`Character.tsx` (client component)
```tsx
"use client";

import { useCallback } from "react";
import { graphql, FragmentOf, readFragment } from "gql.tada";

export const CharacterFragment = graphql(`
  fragment Character on Character {
    name
  }
`);

export default function Character({
  character,
}: {
  character: FragmentOf<typeof CharacterFragment> | null;
}) {
  const { name } = readFragment(character);

  const onClick = useCallback(() => {
    console.log(`Hi, my name is ${name}`);
  }, [name]);

  return <button onClick={onClick}>{name}</button>;
}
```

The following error is thrown:

```
Error: Cannot access definitions.Symbol(Symbol.iterator) on the server. You cannot dot into a client module from a server component. You can only pass the imported name through.
    at Object.get (node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:253976)
    at graphql (webpack-internal:///(rsc)/./node_modules/gql.tada/dist/gql-tada.mjs:20:23)
    at eval (webpack-internal:///(rsc)/./src/app/page.tsx:14:64)
    at (rsc)/./src/app/page.tsx (.next/server/app/page.js:248:1)
    at Function.__webpack_require__ (.next/server/webpack-runtime.js:33:42)
    at async e5 (node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:396551)
    at async tv (node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:400209)
    at async tb (node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:400770)
    at async tb (node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:400901)
    at async tj (node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:36:2130)
    at async node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:36:2722
```

Is there some way to make this pattern work?

### Reproduction

https://github.com/hrougier/gql.tada

### gql.tada version

gql.tada v1.5.1

### Validations

- [X] I can confirm that this is a bug report, and not a feature request, RFC, question, or discussion, for which [GitHub Discussions](https://github.com/0no-co/gql.tada/discussions) should be used
- [X] Read the [docs](https://gql-tada.0no.co/).
- [X] Follow our [Code of Conduct](https://github.com/0no-co/gql.tada/blob/main/CODE_OF_CONDUCT.md)

**Comment by JoviDeCroock** [comment]
This is because `CharacterFragment` is considered part of the client-module, hence when we try to merge the `definitions` (fragments) of said client export in the main operation we are dis-allowed. I don't really understand this limitation but it seems like one that Next chose conciously, not much we can do about that though.

**Comment by kitten** [comment]
Closing due to inactivity and since — seemingly — at least, we can't do much about this. My hope is that the React/Next teams support shared exports from client-component modules in the future to support colocated exports.

**Comment by neefrehman** [comment]
I've opened an issue about this with Next at https://github.com/vercel/next.js/issues/71369. From what I've seen previously (and referenced in the issue) there should have been a fix for this, which has potentially regressed?

**Comment by neefrehman** [comment]
There was an update from the Next team related to this in https://github.com/vercel/next.js/issues/75192#issuecomment-2629016605. I guess this means that the fragment documents created by `gql.tada` are not one of [the following serializable types](https://react.dev/reference/rsc/use-client#serializable-types)? I'm imagining that specifically `definitions` does not meet the criteria of  "Iterables containing serializable values".

**Comment by macrozone** [comment]
> [@kitten](https://github.com/kitten) Do you think a fix might theoretically be possible? Not being able to use fragments defined in client component scope seriously hinders fragment colocation…

ideally you then put the fragment next to the client component in a separate file to avoid this problem. For me its co-located enough.

often, when you have a client component, there is a pattern where you can introduce another component that has not a "use client" directive and can be imported in both places - and with the fragment in the same file.

I also find it sometimes annoying dealing with this problem, also because the resulting error is obscure, however its always an invitation to refactor a bit.

Also claude code, cursor and co make this a minor problem if you just brief them correctly how to use gql.tada (in a claude.md or skill)
