### ISSUE TITLE
RangeError: Maximum call stack size exceeded running `bun x gql.tada turbo`

### ISSUE THREAD

**Issue by deathemperor** [0no-co/gql.tada#374]
### Describe the bug

Reproducible repo's private, I've added @kitten.

full stack trace:

```
 ⚠ Unexpected Error
Could not build cache
┗ RangeError: Maximum call stack size exceeded
      at getTextOfNode (/Users/deathemperor/papaya/cassava_sample/node_modules/typescript/lib/typescript.js:16618:23)
      at declarationNameToString (/Users/deathemperor/papaya/cassava_sample/node_modules/typescript/lib/typescript.js:17303:60)
      at getNameOfSymbolAsWritten (/Users/deathemperor/papaya/cassava_sample/node_modules/typescript/lib/typescript.js:58458:16)
      at createExpressionFromSymbolChain (/Users/deathemperor/papaya/cassava_sample/node_modules/typescript/lib/typescript.js:55959:27)
      at symbolToExpression (/Users/deathemperor/papaya/cassava_sample/node_modules/typescript/lib/typescript.js:55952:14)
      at symbolToNode (/Users/deathemperor/papaya/cassava_sample/node_modules/typescript/lib/typescript.js:54160:14)
      at /Users/deathemperor/papaya/cassava_sample/node_modules/typescript/lib/typescript.js:54068:144
      at withContext2 (/Users/deathemperor/papaya/cassava_sample/node_modules/typescript/lib/typescript.js:54191:29)
      at symbolToNode (/Users/deathemperor/papaya/cassava_sample/node_modules/typescript/lib/typescript.js:54068:80)
      at symbolToStringWorker (/Users/deathemperor/papaya/cassava_sample/node_modules/typescript/lib/typescript.js:53958:22)
      at usingSingleLineStringWriter (/Users/deathemperor/papaya/cassava_sample/node_modules/typescript/lib/typescript.js:16324:5)
      at symbolToString (/Users/deathemperor/papaya/cassava_sample/node_modules/typescript/lib/typescript.js:53956:62)
      at Object.symbolToString (/Users/deathemperor/papaya/cassava_sample/node_modules/typescript/lib/typescript.js:50103:14)
      at createDefinitionInfo (/Users/deathemperor/papaya/cassava_sample/node_modules/typescript/lib/typescript.js:170045:31)
      at /Users/deathemperor/papaya/cassava_sample/node_modules/typescript/lib/typescript.js:170001:40
      at map (/Users/deathemperor/papaya/cassava_sample/node_modules/typescript/lib/typescript.js:2586:19)
      at getDefinitionFromSymbol (/Users/deathemperor/papaya/cassava_sample/node_modules/typescript/lib/typescript.js:170001:10)
      at Object.getDefinitionAtPosition (/Users/deathemperor/papaya/cassava_sample/node_modules/typescript/lib/typescript.js:169760:120)
      at Object.getDefinitionAtPosition2 (/Users/deathemperor/papaya/cassava_sample/node_modules/typescript/lib/typescript.js:149301:38)
      at Object.getDefinitionAtPosition (file:///Users/deathemperor/papaya/cassava_sample/node_modules/@gql.tada/cli-utils/dist/chunks/index-chunk.mjs:4872:14)
      at unrollFragment (file:///Users/deathemperor/papaya/cassava_sample/node_modules/@gql.tada/cli-utils/node_modules/@0no-co/graphqlsp/dist/chunks/api-chunk.mjs:1632:29)
      at unrollFragment (file:///Users/deathemperor/papaya/cassava_sample/node_modules/@gql.tada/cli-utils/node_modules/@0no-co/graphqlsp/dist/chunks/api-chunk.mjs:1660:12)
      at unrollFragment (file:///Users/deathemperor/papaya/cassava_sample/node_modules/@gql.tada/cli-utils/node_modules/@0no-co/graphqlsp/dist/chunks/api-chunk.mjs:1660:12)
      at unrollFragment (file:///Users/deathemperor/papaya/cassava_sample/node_modules/@gql.tada/cli-utils/node_modules/@0no-co/graphqlsp/dist/chunks/api-chunk.mjs:1660:12)
      at unrollFragment (file:///Users/deathemperor/papaya/cassava_sample/node_modules/@gql.tada/cli-utils/node_modules/@0no-co/graphqlsp/dist/chunks/api-chunk.mjs:1660:12)
```
I've removed most of production source code from the repo in hope of finding the root causes. With full source code it runs infinitely without any errors thrown, when trying to stop (ctrl+c) it hangs. I can give you access to full repo too if needed (maybe this one first?).

This has been happening for quite some time when turbo cmd was released. I decided to wait for more releases before posting until now. This is the last piece that provides the last 10% that would complete our migration to gql.tada. Our DX with gql.tada has been great, never thought codegen was that problematic.

### Reproduction

https://github.com/papaya-insurtech/cassava_sample/

### gql.tada version

gql.tada 1.8.5

### Validations

- [X] I can confirm that this is a bug report, and not a feature request, RFC, question, or discussion, for which [GitHub Discussions](https://github.com/0no-co/gql.tada/discussions) should be used
- [X] Read the [docs](https://gql-tada.0no.co/).
- [X] Follow our [Code of Conduct](https://github.com/0no-co/gql.tada/blob/main/CODE_OF_CONDUCT.md)

**Comment by deathemperor** [comment]
@kitten thanks for the change. Do you mind checking the full repo too?

in the full repo, it runs indefinitely

```
bun x gql.tada turbo
⠧ Scanning files…
```

(the `⠧` anim doesn't stop until `ctrl+c` is pressed)
